pipeline:
  name: input set
  identifier: input_set
  projectIdentifier: proj1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: step1
                  identifier: step1
                  type: HarnessApproval
                  timeout: <+input>
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
