pipeline:
  name: p1_remote
  identifier: p1_remote
  projectIdentifier: proj1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Deployment
        spec:
          serviceConfig:
            serviceRef: srv1
            serviceDefinition:
              spec: {}
              type: Kubernetes
          infrastructure:
            infrastructureDefinition:
              type: KubernetesDirect
              spec:
                connectorRef: k8s_con
                namespace: n1
                releaseName: release-<+INFRA_KEY>
            allowSimultaneousDeployments: false
            environmentRef: env2
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: exit 0
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
