pipeline:
  name: p1_remote
  identifier: p1_remote
  projectIdentifier: proj1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: ap1
                  identifier: ap1
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
  notificationRules:
    - name: notf
      identifier: notf
      pipelineEvents:
        - type: StageFailed
          forStages:
            - AllStages
        - type: PipelineFailed
      notificationMethod:
        type: Email
        spec:
          userGroups: []
          recipients:
            - vivek.dixit@harness.io
      enabled: true
