pipeline:
  name: p1_vivek_remote_def
  identifier: p1_vivek_remote_def
  projectIdentifier: svcredesignhinger
  orgIdentifier: harness
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: nginx
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: exit 0
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps: []
          environments:
            metadata:
              parallel: true
            values:
              - environmentRef: delegateEnv
                deployToAll: false
                infrastructureDefinitions:
                  - identifier: infra2
                  - identifier: infra3
              - environmentRef: qa
                deployToAll: true
                infrastructureDefinitions: <+input>
              - environmentRef: env_remote_vivek_qa
                deployToAll: false
                infrastructureDefinitions:
                  - identifier: infra_inline
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
