pipeline:
  name: remote_pipeline_vivek
  identifier: remote_pipeline_vivek
  projectIdentifier: naidusanity
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: ap1
                  identifier: ap1
                  template:
                    templateRef: app_stage_temp_vivek
                    versionLabel: v1
        tags: {}
