pipeline:
  name: Test_webhook
  identifier: Test_webhook
  projectIdentifier: DoNotDelete_AmitSingh
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: k8
        identifier: k8
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: s1
          environment:
            environmentRef: E1
            deployToAll: false
            infrastructureDefinitions:
              - identifier: I1
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "jjj"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Swap primary with stage service
                  identifier: rollbackBgSwapServices
                  type: K8sBGSwapServices
                  timeout: 10m
                  spec:
                    skipDryRun: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
