pipeline:
  name: test_config
  identifier: test_config
  projectIdentifier: naidusanity
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        template:
          templateRef: app_stage
          versionLabel: v1
          gitBranch: b1
