pipeline:
  name: Test_webhook
  identifier: Test_webhook
  projectIdentifier: DoNotDelete_AmitSingh
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: k8
        identifier: k8
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: s1
          environment:
            environmentRef: E1
            deployToAll: false
            infrastructureDefinitions:
              - identifier: I1
          execution:
            steps:
              - step:
                  type: K8sRollingDeploy
                  name: K8sRollingDeploy_1
                  identifier: K8sRollingDeploy_1
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Swap primary with stage service
                  identifier: rollbackBgSwapServices
                  type: K8sBGSwapServices
                  timeout: 10m
                  spec:
                    skipDryRun: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
